require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*
    - Rakefile
    - Gemfile
    - config/**/*
    - notepad/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - test/**/*
    - db/**/*

RSpec/FilePath:
  Enabled: false
  CustomTransform:
    RuboCop: rubocop
    RSpec: rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleWording:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

TrailingCommaInLiteral:
  Enabled: false

TrailingCommaInArguments:
  Enabled: false

Documentation:
  Enabled: false

AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
